In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import log, pi

In [7]:
np.var(np.array([[1,2],[2,1]]), axis=0)

array([0.25, 0.25])

# 2. Naive Bayes tradicional

# 3. Análise de Discriminante Gaussiano

# 1. Naive Bayes Gaussiano

In [2]:
blobs2 = pd.read_csv("../data/blobs2.csv", names=["x1", "x2", "y"])
len_2 = blobs2.shape[0]

def train(dataset, tamanho):
    classes = {}
    # Separando as classes
    for i in range(0, tamanho):
        row = [x for x in np.array(dataset.iloc[[i]])[0]]
        if row[-1] not in classes:
            classes[row[-1]] = []
        classes[row[-1]].append(row[:2])
    
    # Calculando média e covariancia
    mean_variance_classes = {}

    for key in classes.keys():
        mean_variance_classes[key] = {}
        mean_variance_classes[key]['mean'] = np.mean(np.array(classes[key]), axis=0)
        mean_variance_classes[key]['var'] = np.var(np.array(classes[key]), axis=0)             
    
    return mean_variance_classes

def predict(dict_means, tamanho, teste):
    # Ver onde vou encaixar esse somatório
    function = lambda mean, cov, x, pck: -0.5 * log((2*pi*cov)) - (1/(2*cov))*((x - mean)**2) + log(pck)
    probs = []
    pck = len(dict_means.keys())/tamanho;
    for key in dict_means.keys():
        somatorio = 0
        for i in range(0, len(dict_means[key]['mean'])):
            somatorio += function(dict_means[key]['mean'][i], dict_means[key]['var'][i], x[i], pck)
        probls.append({key: somatorio})
classes = train(blobs2, len_2)
classes


NameError: name 'pd' is not defined

In [ ]:
#media = np.mean(classes[key])
            #variancia = [ for x in ]
            # para cada dimensão media e variancia
            #mean_covariance_classes[key] = (np.mean(classes[key]), 

In [4]:
np.mean(np.array([[1,2],[2,1]]), axis=0)

array([1.5, 1.5])

In [5]:
np.cov(np.array([[1,2],[2,1]]))

array([[ 0.5, -0.5],
       [-0.5,  0.5]])